export const LOGO_HEIGHT_TOKENS = {
  MAIN_MOBILE: 49,
  MAIN_DESKTOP: 76,
  SIGN_IN_MOBILE: 56,
  SIGN_IN_DESKTOP: 80,
  LANDING_NAV: 46,
  LANDING_FOOTER: 32,
} as const;

export const MAIN_MOBILE_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.MAIN_MOBILE;
export const MAIN_DESKTOP_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.MAIN_DESKTOP;
export const SIGN_IN_MOBILE_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.SIGN_IN_MOBILE;
export const SIGN_IN_DESKTOP_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.SIGN_IN_DESKTOP;
export const LANDING_NAV_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.LANDING_NAV;
export const LANDING_FOOTER_LOGO_HEIGHT = LOGO_HEIGHT_TOKENS.LANDING_FOOTER;

// Backward-compatible aliases
export const DASHBOARD_MOBILE_LOGO_HEIGHT = MAIN_MOBILE_LOGO_HEIGHT;
export const DASHBOARD_DESKTOP_LOGO_HEIGHT = MAIN_DESKTOP_LOGO_HEIGHT;
export const AUTH_MOBILE_LOGO_HEIGHT = SIGN_IN_MOBILE_LOGO_HEIGHT;
export const AUTH_DESKTOP_LOGO_HEIGHT = SIGN_IN_DESKTOP_LOGO_HEIGHT;
