export const DASHBOARD_DESKTOP_LOGO_HEIGHT = 60;
export const DASHBOARD_MOBILE_LOGO_HEIGHT = 45;
export const AUTH_DESKTOP_LOGO_HEIGHT = 66;
export const AUTH_MOBILE_LOGO_HEIGHT = 52;
export const LANDING_NAV_LOGO_HEIGHT = 58;
export const LANDING_FOOTER_LOGO_HEIGHT = 32;
